# codecov.yml

comment:
    layout: "header, diff, flags, components" 
  
  component_management:
    default_rules:  
      statuses:
        - type: project
          target: auto
          branches:
            - "!main"
  
    individual_components:
      - component_id: paralax_core
        name: Paralax Core
        paths:
          - src/Paralax/**
  
      - component_id: paralax_cqrs_commands
        name: Paralax CQRS Commands
        paths:
          - src/Paralax.CQRS.Commands/**
  
      - component_id: paralax_cqrs_queries
        name: Paralax CQRS Queries
        paths:
          - src/Paralax.CQRS.Queries/**
  
      - component_id: paralax_http
        name: Paralax HTTP
        paths:
          - src/Paralax.HTTP/**
  
      - component_id: paralax_security
        name: Paralax Security
        paths:
          - src/Paralax.Security/**
  